dist: trusty
language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

matrix:
  allow_failures:
    - php: "7.2"
      env: DOKUWIKI=stable
    - php: "7.1"
      env: DOKUWIKI=stable

env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
  - DOKUWIKI=old-stable

before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh

install:
  - sh travis.sh

before_script:
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - cd _test

script:
  - if [ "$DOKUWIKI" = "master" ]; then PRESERVE_TMP=false phpunit --stderr --group plugin_yalist --verbose --debug; fi
  - if [ "$DOKUWIKI" != "master" ]; then PRESERVE_TMP=false php ../phpunit-5.7.phar --stderr --group plugin_yalist --verbose --debug; fi
